### ISSUE TITLE
询问PRCV2019大田作物病害图像识别技术挑战赛数据集

### ISSUE THREAD

**Issue by dxqlovestudy** [wuyuejinxia/gokv#1]
我是在github上面看到你2019年在PRCV上面的源码，想请问一下您还保存了当时的数据集吗？如果有的话，麻烦给我复制一份，请您喝杯咖啡O(∩_∩)O，因为需要那个数据集，做相关的目标检测算法。
可以留个联系方式吗？邮箱，微信都可以。

**Comment by wuyuejinxia** [comment]
链接: https://pan.baidu.com/s/1i_iO3JXgvVu93DQral6LQQ 提取码: afu2 复制这段内容后打开百度网盘手机App，操作更方便哦
--来自百度网盘超级会员v5的分享
在 2022年10月20日 +0800 PM8:50，dxqlovestudy ***@***.***>，写道：

**Comment by dxqlovestudy** [comment]
这个不是我想要的，但是还是非常感谢，我已经找到数据了。
